add more details on missing $ref
APIDevTools/json-schema-ref-parser pull request #193
Opened 2020-09-10 21:02 UTC by AlexHolly

Example Current infos:
https://apitools.dev/swagger-parser/online/

```
openapi: 3.0.2
info:
  description: >-
    This is a sample server Petstore server.
  version: 1.0.0
  title: Swagger Petstore
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /pet:
    post:
      tags:
        - pet
      parameters:
        - $ref: '#/components/parameters/invalid'
components:
  parameters:
    petId:
      name: petId
      in: path
      required: true
      schema:
        type: integer
        format: int64
```

PR will give this data

```
$ref value of: #/paths/~1pet/post/parameters/0 
  is missing target: #/components/parameters/ThisIsmissing
  found: #/components/parameters
```

2020-10-06 08:53 UTC, JamesMessinger commented
Hi @AlexHolly.  Thank you for the PR. It looks like that code should probably go inside the  `MissingPointerError` class instead (with additional data passed as parameters to the constructor).

2020-10-06 15:39 UTC, AlexHolly commented
Done.

2021-06-01 07:13 UTC, P0lip requested changes
Besides the TS definition, a minor test update would be cool.
We presumably already have some tests for `MissingPointerError`, thus adding an additional assertion should be sufficient, no need to write a new case.

2021-06-01 07:13 UTC, P0lip commented on lib/util/errors.js
>  const MissingPointerError = exports.MissingPointerError = class MissingPointerError extends JSONParserError {
Could you please update the TS definitions as well?

2023-02-03 19:52 UTC, jonluca commented
This PR looks good - apologies for the long delay here @AlexHolly 

If you rebase this onto latest I'll merge it in.

2023-02-06 00:28 UTC, AlexHolly commented
@jonluca I am unable to test it with https://github.com/APIDevTools/swagger-parser looks like it expects .js files. Is there a command to build them?

2023-09-18 23:45 UTC, closed without merging